// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDSwmQgImC3P4mbrWLT0nIROxUDt98DWY',
    appId: '1:948932157902:web:5b67b2878ad966025acb9f',
    messagingSenderId: '948932157902',
    projectId: 'gsheetauth',
    authDomain: 'gsheetauth.firebaseapp.com',
    storageBucket: 'gsheetauth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbOEs_E3sfpeBuJp2uTlMzDrPr8iNYC2I',
    appId: '1:948932157902:android:216d2d7ac0b1b41d5acb9f',
    messagingSenderId: '948932157902',
    projectId: 'gsheetauth',
    storageBucket: 'gsheetauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6is8L2opGkIRFgK4gv_DxaEoxzUzY9bQ',
    appId: '1:948932157902:ios:e785fc88352423735acb9f',
    messagingSenderId: '948932157902',
    projectId: 'gsheetauth',
    storageBucket: 'gsheetauth.appspot.com',
    iosClientId: '948932157902-duscuuph5knq7v99s8d93m590unnjdel.apps.googleusercontent.com',
    iosBundleId: 'com.example.pizzaPlanet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6is8L2opGkIRFgK4gv_DxaEoxzUzY9bQ',
    appId: '1:948932157902:ios:b959bb409e1bccf75acb9f',
    messagingSenderId: '948932157902',
    projectId: 'gsheetauth',
    storageBucket: 'gsheetauth.appspot.com',
    iosClientId: '948932157902-t1du0nt1f2tt0a9op2alu8jm0qb1m2al.apps.googleusercontent.com',
    iosBundleId: 'com.example.pizzaPlanet.RunnerTests',
  );
}
